name: newsappflutter
description: newsappflutter.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cached_network_image: ^3.2.1
  cupertino_icons: ^1.0.4
  flutter:
    sdk: flutter
  google_fonts: ^3.0.1
  http: ^0.13.4
  lint: ^1.8.2
  webview_flutter: ^3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
